---
title: "Historic Redlining"
format: gfm
---
 
Historic redlining data refers to data from the Home Owners' Loan Corporation (HOLC) that created residential security maps in the 1930s, which contributed to racial segregation and disinvestment in minority neighborhoods. One popular source for this data is the Mapping Inequality project (https://dsl.richmond.edu/panorama/redlining/).

In this example, we'll download historic redlining data for Philadelphia in the form of a GeoJSON file and analyze the data in R and Python.

R:
In R, we'll use the 'sf' and 'dplyr' packages to read and process the GeoJSON data.

R code:

```{r, cache=TRUE}
# Install and load necessary libraries]
library(knitr)
library(sf)
library(dplyr)

# Download historic redlining data for Philadelphia
url <- "https://dsl.richmond.edu/panorama/redlining/static/downloads/geojson/PAPhiladelphia1937.geojson"
philly_geojson <- read_sf(url)

# Count the number of areas per HOLC grade
grade_counts <- philly_geojson %>%
  group_by(holc_grade) %>%
  summarize(count = n())

kable(philly_geojson)
plot(grade_counts)
```


Python:
In Python, we'll use the 'geopandas' library to read and process the GeoJSON data.

Python code:

```{python, cache=TRUE}
# Install necessary libraries


import geopandas as gpd

# Download historic redlining data for Philadelphia
url = "https://dsl.richmond.edu/panorama/redlining/static/downloads/geojson/PAPhiladelphia1937.geojson"
philly_geojson = gpd.read_file(url)

# Count the number of areas per HOLC grade
grade_counts = philly_geojson["holc_grade"].value_counts()
print(grade_counts)
```


In conclusion, both R and Python offer efficient ways to download and process historic redlining data in the form of GeoJSON files. The 'sf' package in R provides a simple way to read and manipulate spatial data, while the 'geopandas' library in Python offers similar functionality. The 'dplyr' package in R can be used for data manipulation and analysis, and Python's built-in functions like value_counts() can be used for aggregating data. Depending on your preferred programming language and environment, both options can be effective for working with historic redlining data.