---
title: "American Indian and Alaska Native Areas"
author: "Ty Tuff, ESIIL Data Scientist"
date: "2023-05-21"
format: gfm
editor_options: 
  markdown: 
    wrap: 72
---

The National American Indian/Alaska Native/Native Hawaiian (AIANNH) Areas Shapefile is a dataset that provides a comprehensive view of the geographic, demographic, and cultural landscape of Indigenous communities in the United States. This unique resource comprises diverse legal entities, encompassing federally recognized American Indian reservations, off-reservation trust lands, Alaska Native regional corporations, and Native Hawaiian homelands.

These entities hold a rich tapestry of diverse cultures, languages, and histories, each with unique stories to tell and invaluable wisdom to impart. The AIANNH Areas Shapefile is more than just a collection of data; it is a detailed map of vibrant communities and proud nations, embodying the resilience and enduring spirit of the Indigenous peoples of America.

For researchers, policy makers, educators, and anyone with a vested interest in understanding these communities and their contributions to the broader cultural fabric of the United States, this dataset serves as a vital resource. Its depth and breadth offer unprecedented insights into the geographic boundaries that define these communities, the demographic characteristics that diversify them, and the cultural aspects that unify and distinguish them.

From the wild expanses of Alaska to the lush tropical landscapes of Hawaii, and across the vast American mainland, the AIANNH Areas Shapefile traces the footsteps of the First Nations. By diving into this dataset, you are not only exploring data, but also appreciating the rich tapestry of cultures that form an integral part of the United States' historical, present, and future narrative.

<https://catalog.data.gov/dataset/tiger-line-shapefile-2020-nation-u-s-american-indian-alaska-native-native-hawaiian-aiannh-areas> 


R code:

```{r, cache=TRUE}
# Install and load necessary libraries
library(sf)
library(dplyr)
library(knitr)

# Download dataset from source
url <- "https://www2.census.gov/geo/tiger/TIGER2020/AIANNH/tl_2020_us_aiannh.zip"
temp_file <- tempfile(fileext = ".zip")
download.file(url, temp_file, mode = "wb")
unzip(temp_file, exdir = tempdir())

# Read the Shapefile
shapefile_path <- file.path(tempdir(), "tl_2020_us_aiannh.shp")
aiannh <- read_sf(shapefile_path)

# Count the number of AIANNH per congressional district
state_counts <- aiannh %>%
  group_by(LSAD) %>%
  summarize(count = n())

kable(state_counts[order(-state_counts$count),])
```



Python code:

```{python, cache=TRUE}
import geopandas as gpd
import pandas as pd
import requests
import zipfile
import os
from io import BytesIO

# Download historic redlining data for Philadelphia
url = "https://www2.census.gov/geo/tiger/TIGER2020/AIANNH/tl_2020_us_aiannh.zip"
response = requests.get(url)
zip_file = zipfile.ZipFile(BytesIO(response.content))

# Extract Shapefile
temp_dir = "temp"
if not os.path.exists(temp_dir):
    os.makedirs(temp_dir)

zip_file.extractall(path=temp_dir)
shapefile_path = os.path.join(temp_dir, "tl_2020_us_aiannh.shp")

# Read the Shapefile
aiannh = gpd.read_file(shapefile_path)

# Count the number of AIANNH per congressional district
state_counts = aiannh.groupby("LSAD").size().reset_index(name="count")

# Sort by descending count
state_counts_sorted = state_counts.sort_values(by="count", ascending=False)

print(state_counts_sorted)
```

